import type { ChoiceDefinition, ChoiceId } from "../game/model";

export const choiceDefinitions: Record<ChoiceId, ChoiceDefinition> = {
  "infant-a": {
    id: "infant-a", key: "A", title: "给孩子最好的起点。",
    action: "授权健康监测、知识接入、情绪分析和终身模型训练。",
    risk: "芯片产生的数据将用于训练城市模型，撤回授权目前没有成功案例。",
    deltas: { autonomy: -1, discernment: 1, security: 2 },
    addFlags: ["全量芯片", "终身数据授权"],
    immediateOutcome: ["解锁全量健康监测和AI精英教育通道。", "“栖”默认拥有主动提醒和干预权限。"],
    delayedEcho: "幼年可直接接收答案，青年更易获得高保障职业，老年删除数据需额外申请。",
  },
  "infant-b": {
    id: "infant-b", key: "B", title: "可以帮助，但不能替他决定。",
    action: "开放健康和知识功能，关闭情绪干预与自动决策。",
    risk: "会降低部分预测精度，也可能无法进入最高级别的教育通道。",
    deltas: { autonomy: 1, discernment: 1, security: 1 },
    addFlags: ["监护型芯片", "人类确认权"],
    immediateOutcome: ["获得基础健康监测和知识接入。", "解锁“要求人工确认”和“查看证据来源”。"],
    delayedEcho: "少年和中年更容易要求人工复核，老年可自主划定记忆保存范围。",
  },
  "infant-c": {
    id: "infant-c", key: "C", title: "他的身体不是公共数据库。",
    action: "拒绝神经植入，只保留可随时关闭的外部AI终端。",
    risk: "会失去部分公共教育和预防医疗资格，并需签署风险自担声明。",
    deltas: { autonomy: 2, connection: 1, security: -1 },
    addFlags: ["无植入", "个人数据权"],
    immediateOutcome: ["无法获得实时知识和完整健康预测。", "数据归主角家庭所有。"],
    delayedEcho: "幼年进入线下实验班，青年部分高保障职业不开放，老年可直接选择删除数据。",
  },
  "childhood-a": {
    id: "childhood-a", key: "A", title: "既然答案已经存在，为什么还要重复劳动？",
    action: "直接提交“栖”生成并自动排版的报告。",
    risk: "无法知道错误出现时应从哪里查找。",
    deltas: { discernment: -1, security: 1, meaning: -1 },
    addFlags: ["答案依赖"],
    immediateOutcome: ["获得优异成绩和更多教育资源。", "与小满的关系没有加深。"],
    delayedEcho: "少年期难以立即识别伪造引用，“栖”会更主动跳过解释、直接提供结论。",
  },
  "childhood-b": {
    id: "childhood-b", key: "B", title: "把答案拆开，我要知道你为什么这样判断。",
    action: "要求AI标出每一条结论的原始来源和不确定性。",
    risk: "完整验证需要七小时二十三分钟，报告不会给出完整的标准答案。",
    deltas: { autonomy: 1, discernment: 2, meaning: 1 },
    addFlags: ["查证习惯"],
    immediateOutcome: ["学会查看来源、置信度和遗漏数据。", "“栖”开始在答案中主动标注不确定性。"],
    delayedEcho: "少年期可发现偏见训练样本，中年期可检查医疗AI的成本计算方式。",
  },
  "childhood-c": {
    id: "childhood-c", key: "C", title: "先看看真实世界，再回来问AI。",
    action: "和小满到旧公园进行实地调查。",
    risk: "标准化成绩只有B，单次观察不足以证明因果关系。",
    deltas: { connection: 2, meaning: 1 },
    addFlags: ["小满羁绊", "线下协作"],
    immediateOutcome: ["与小满建立重要关系。", "获得“现实调查”评价。"],
    delayedEcho: "少年期小满会主动求助，壮年和中年危机中小满及社区可能提供现实支持。",
  },
  "teen-a": {
    id: "teen-a", key: "A", title: "系统可能不完美，但风险不能被忽视。",
    action: "签署同伴行为观察报告，相信风险预测。",
    risk: "小满被送往行为矫正学校，林一确认的可能是系统替他写好的未来。",
    deltas: { autonomy: -1, connection: -2, security: 2 },
    addFlags: ["制度信任", "小满关系中断"],
    immediateOutcome: ["获得城市奖学金和高保障升学资格。", "与小满的关系中断。"],
    delayedEcho: "最优人生合同的幸福预测更高，但壮年危机缺少小满和线下社区支持。",
  },
  "teen-b": {
    id: "teen-b", key: "B", title: "先证明这个预测值得相信。",
    action: "调查模型依据，并将申诉过程直播到学生公共频道。",
    risk: "失去可信学生资格；没有查证习惯时，申诉会在个案层面失败。",
    deltas: { discernment: 1, connection: 1, meaning: 1, publicInfluence: 2 },
    addFlags: ["公开申诉"],
    immediateOutcome: ["保留或重新建立与小满的关系。", "公共影响力显著上升。"],
    delayedEcho: "青年期解锁决策顾问公共奖学金，中年期可将申诉案作为医疗算法审查先例。",
  },
  "teen-c": {
    id: "teen-c", key: "C", title: "我先救眼前的人，制度以后再说。",
    action: "秘密帮助小满删除记录并逃离学校。",
    risk: "被标记为“不透明用户”，失去部分升学和职业资格。",
    deltas: { autonomy: 1, connection: 2, security: -1, publicInfluence: 1 },
    addFlags: ["地下互助", "小满羁绊"],
    immediateOutcome: ["小满进入未联网的地下互助社区。", "林一失去部分升学和职业资格。"],
    delayedEcho: "青年可加入现实社区路线，中年非法治疗可获得地下网络支持。",
  },
  "youth-a": {
    id: "youth-a", key: "A", title: "如果它真的更了解我，为什么不听？",
    action: "接受最优人生合同，成为机器人人格设计师。",
    risk: "“栖”扩大日程与情绪干预权限，晚年可能留下被托管的一生。",
    deltas: { autonomy: -1, security: 2 },
    addFlags: ["最优人生合同", "人格设计师"],
    immediateOutcome: ["获得高收入、住房和医疗保障。", "“栖”扩大日程与情绪干预权限。"],
    delayedEcho: "壮年职业会被新一代人格模型自动化，并获得精英延寿计划资格入口。",
  },
  "youth-b": {
    id: "youth-b", key: "B", title: "AI可以计算后果，但不能替人承担后果。",
    action: "成为决策顾问，帮助普通人在算法选项中作价值判断。",
    risk: "收入稳定但不优渥；没有早期相关标记时需要承担学生贷款。",
    deltas: { discernment: 1, meaning: 2, publicInfluence: 1 },
    addFlags: ["决策顾问", "人类责任"],
    immediateOutcome: ["开始接触生育、医疗、教育和数字人格伦理案件。", "获得稳定但不优渥的收入。"],
    delayedEcho: "壮年可转入公共AI审查委员会，中年获得正式医疗申诉渠道。",
  },
  "youth-c": {
    id: "youth-c", key: "C", title: "我宁愿承担自己选错的后果。",
    action: "放弃城市合同，进入现实社区工作。",
    risk: "住房、职业和医疗资源需要重新排队，系统无法保证原幸福概率。",
    deltas: { autonomy: 2, connection: 1, meaning: 1, security: -1 },
    addFlags: ["拒绝预测", "社区工作者"],
    immediateOutcome: ["收入和医疗额度较低。", "获得较强自主性和现实关系。"],
    delayedEcho: "壮年拥有现实互助网络但缺乏精英延寿资格，中年可通过社区分担成本。",
  },
  "adulthood-a": {
    id: "adulthood-a", key: "A", title: "既然机器会工作，我就决定机器为谁工作。",
    action: "成为AI平台管理者，分配机器人任务和高等级服务。",
    risk: "日常工作逐渐只剩签字，“栖”会在睡眠中预处理决定。",
    deltas: { autonomy: -1, connection: -1, security: 2 },
    addFlags: ["平台管理者", "精英延寿资格"],
    immediateOutcome: ["获得大量财富、高级医疗额度和延寿资格。", "与现实朋友和家人的相处时间减少。"],
    delayedEcho: "延续最优人生合同的高保障路线，也可能被要求交出更多私人数据。",
  },
  "adulthood-b": {
    id: "adulthood-b", key: "B", title: "我继续工作，因为有些责任不能外包。",
    action: "加入公共AI审查合作社，公开保存非决定性AI建议。",
    risk: "生活稳定但不富裕，可能失去部分商业收入。",
    deltas: { connection: 1, meaning: 2, publicInfluence: 2 },
    addFlags: ["公共服务", "AI责任倡议"],
    immediateOutcome: ["获得公共信任和制度参与资格。", "AI意见作为非决定性建议被公开保存。"],
    delayedEcho: "推动共生治理和规则塑造者路线。",
  },
  "adulthood-c": {
    id: "adulthood-c", key: "C", title: "如果不必工作，我想体验更多种人生。",
    action: "进入全感官虚拟世界“昼海”。",
    risk: "现实关系逐渐弱化；没有小满羁绊时，现实通讯列表会逐年变短。",
    deltas: { security: 1, connection: -2, meaning: 1 },
    addFlags: ["昼海居民"],
    immediateOutcome: ["获得丰富体验和较高短期满足。", "现实关系逐渐弱化。"],
    delayedEcho: "有小满羁绊时保留离线夜；无羁绊时现实危机可能无人到场。",
  },
  "midlife-a": {
    id: "midlife-a", key: "A", title: "不能因为她是我的母亲，就否定对所有人更公平的计算。",
    action: "接受AI医疗判定，不再申诉。",
    risk: "周岚离世，且自主性低时系统会默认启用数字周岚。",
    deltas: { autonomy: -1, security: 1, meaning: -2 },
    addFlags: ["接受医疗判定", "数字周岚"],
    immediateOutcome: ["保留保障和个人医疗资源。", "周岚离世，林一获得数字母亲。"],
    delayedEcho: "政策转向技术优先，数字周岚可进入昼海虚拟住所。",
  },
  "midlife-b": {
    id: "midlife-b", key: "B", title: "如果没有人愿意签名，就不能让机器独自拒绝。",
    action: "要求人类复核，并追问谁为拒绝治疗负责。",
    risk: "消耗财富、时间和医疗额度；不满足条件时复核维持原判。",
    deltas: { autonomy: 1, security: -1, publicInfluence: 2 },
    addFlags: ["人类复核"],
    immediateOutcome: ["启动对医疗AI的公开听证。", "成功时周岚多活数年；失败时保留完整告别过程。"],
    delayedEcho: "政策可能转向共生治理。",
  },
  "midlife-c": {
    id: "midlife-c", key: "C", title: "规则拒绝救她，我就不再服从规则。",
    action: "绕过系统，调换人工器官分配编号。",
    risk: "会减少另一名未知患者获得治疗的概率，并使主角面临制度处罚。",
    deltas: { autonomy: 2, security: -2, publicInfluence: 1 },
    addFlags: ["非法治疗"],
    immediateOutcome: ["周岚获得效果有限的治疗。", "主角保障显著下降。"],
    delayedEcho: "政策可能转向人本限制，也可能陷入长期社会冲突。",
  },
  "elder-a": {
    id: "elder-a", key: "A", title: "既然还能继续，为什么必须结束？",
    action: "加入永生计划，授权基因修复、器官替换和意识融合。",
    risk: "系统需要访问全部记忆，并可能用AI补全缺失的个人经历。",
    deltas: {},
    addFlags: ["选择永生"],
    immediateOutcome: ["确认后病房逐渐变成数据空间。"],
    delayedEcho: "按保障与延寿资格分流至永续节点或数据幽灵。",
  },
  "elder-b": {
    id: "elder-b", key: "B", title: "我要多一点时间，但不要无限的时间。",
    action: "选择有限延寿，并建立记忆保存边界。",
    risk: "边界会使数字形象不完整，且目标完成后不再自动续延。",
    deltas: {},
    addFlags: ["选择边界"],
    immediateOutcome: ["可完成最后目标，并限制私人对话生成互动人格。"],
    delayedEcho: "按公共影响力和责任制度分流至规则塑造者或有边界的共生。",
  },
  "elder-c": {
    id: "elder-c", key: "C", title: "我的人生不需要永远可调用。",
    action: "停止治疗，撤销数据授权，不生成数字副本。",
    risk: "“栖”无法继续代表主角，也无法证明这些选择曾发生。",
    deltas: {},
    addFlags: ["选择删除"],
    immediateOutcome: ["系统删除职业模型、健康预测、情绪记录和数字人格素材。"],
    delayedEcho: "按真实联结分流至人间余温或无痕离场。",
  },
};
